# Generated by Django 4.2 on 2024-06-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wishlist',
        ),
    ]
