# Generated by Django 4.2 on 2024-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
