# Generated by Django 4.2 on 2024-06-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
